services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: DB
    command: postgres -c max_wal_size=4GB -c shared_preload_libraries=pg_cron -c max_connections=200 -c shared_buffers=256MB -c maintenance_work_mem=1GB -c wal_compression=on
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s      
      timeout: 5s         
      retries: 5      
    ports:
      - "5432:5432"
    networks:
      - example

  data-importer:
    build:
      context: ./Backend
    container_name: Data-Importer
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./Data:/chromosome/Data
      - data_import_volume:/chromosome/import_status
    command: >
      sh -c "
        if [ ! -f /chromosome/import_status/.imported ]; then
          echo 'Start to import data...' &&
          python /chromosome/backend/init_db.py &&
          touch /chromosome/import_status/.imported &&
          echo 'Data imported'
        else
          echo 'Data exists, skip importing'
        fi
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - example
    restart: 'no'  

  redis:
    image: redis:8.0.2-bookworm
    container_name: Redis
    restart: on-failure
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - example

  backend:
    container_name: Backend
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./Backend:/chromosome/backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      data-importer:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "5001:5001"
    networks:
      - example

  frontend:
    container_name: Frontend
    restart: on-failure
    volumes:
      - ./Frontend:/chromosome/frontend:cached
      - frontend_module:/chromosome/frontend/node_modules
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - example

  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - example

  db-cron:
    build:
      context: ./Cron
      dockerfile: Dockerfile
    container_name: DB-Cron
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    command: sh -c 'echo "$${DB_HOST}:$${DB_PORT}:$${DB_NAME}:$${DB_USERNAME}:$${DB_PASSWORD}" > /root/.pgpass && chmod 600 /root/.pgpass && /usr/sbin/crond -f -l 8'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - example

  celery-worker:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: CeleryWorker
    restart: on-failure
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./Backend:/chromosome/backend
    command: >
      sh -c "celery -A celery_worker.celery_worker worker --loglevel=info --concurrency=4"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - example

networks:
  example:
    driver: bridge

volumes:
  frontend_module:
  pgadmin_data:
  data_import_volume:
  pgdata:
  redis_data: